### ISSUE TITLE
Looking forward to adding new features

### ISSUE THREAD

**Issue by Xing-Fax** [emildalalyan/free64-cSharp#1]
After I downloaded the 0.5 version of the program, I found that many functions in the program were not developed. In my test, I found that only the "CPU ID" function was developed. I hope that the system sensor function and some other functions can be added, but there is a problem. 0.5.1 version of the program, it seems to be unable to take effect on my device, there is no display screen, I hope this problem can be fixed, thank you for providing the open source code of this project

我下载了0.5版本的程序后，发现程序中很多功能没有开发。在我的测试中，发现只开发了“CPU ID”功能。我希望可以添加系统传感器功能和其他一些功能，但是有一个问题。 0.5.1版本的程序，在我的设备上好像无法生效，没有显示画面，希望能解决这个问题，谢谢提供这个项目的开源代码

**Comment by emildalalyan** [comment]
### About functions and roadmap
You're almost right, only CPUID and "Operating System" page were made. There's **many** features, which i want to add, and sensors among 'em, but for reading MSR registers i need a driver. But, HDD temp. can be gathered from WMI.

### About problem with start.
There's some questions.
What's your OS?
Did you install .NET 5? If you didn't, download [there](https://dot.net). **Download x86 version of .NET 5, because build is 32-bit**

**Glad to help**

**Comment by Xing-Fax** [comment]
> ### 关于功能和路线图
> 你几乎是对的，只制作了 CPUID 和“操作系统”页面。有**很多**中“时间的功能，我想添加和传感器，但对于阅读MSR寄存器，我需要一个驱动程序。但是，硬盘温度。可以从 WMI 收集。
> 
> ### 关于启动问题。
> 有一些问题。
> 你的操作系统是什么？
> 您是否安装了 .NET 5？如果没有，请[在那里](https://dot.net)下载。**因为构建是 32 位的，所以下载 .NET 5 的 x86 版本**
> 
> **乐意效劳**

My operating system is Windows10 Professional Edition, version number: 2004, operating system version： 19041.264.
After following your suggestion, I reinstalled the NET 5.0 runtime, and it is the x86 version. After running the program, it still cannot run normally. It is the same situation as before the installation. I cannot determine whether it is a problem with my operating system. But the 0.5 version program can be run normally, only the 0.5.1 version cannot be run correctly
If you want to read the sensors of the system, I recommend a GitHub repository, which can read a lot of important information from the system, such as voltage, frequency, temperature, and so on. I have used it in my project. , It provides a lot of help for my program, here is the link to the warehouse: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
Thank you for answering my question

**Comment by emildalalyan** [comment]
And one more question :) Did you install **Desktop Runtime** or just **Runtime**? It is important. **Desktop Runtime** includes libraries to work with Windows-dependent things.

And about **LibreHardwareMonitor**
I'd want to learn smth about gathering hw information, and not just use someone else's code. Maybe i'll take a look at it.

**Comment by Xing-Fax** [comment]
> 还有一个问题 :) 您是安装了**桌面运行时**还是只是**运行时**？这很重要。**桌面运行时**包括用于处理依赖于 Windows 的东西的库。
> 
> 关于**LibreHardwareMonitor，**
> 我想学习收集硬件信息，而使用其他人的代码。也许我会看看它。

Thank you very much for correcting my mistake. After I installed the NET 5.0 desktop runtime, the program can run normally.
I also support you to use your own code to collect hardware information, because I know that using your own code can make the program run more efficiently, and you can also learn other new knowledge. Finally, you successfully helped me solve this problem, thank you
